### ISSUE TITLE
Updating a tag  within the tag activity raises an error

### ISSUE THREAD

**Issue by cnouguier** [kalisio/aktnmap#147] opened 2020-07-09 12:40 UTC
The following error message is raised : `Cannot read property '_id' of nul` and the number of uers assigned to this tag is incremented

**Comment by claustres** [comment] 2020-07-10 10:35
Cannot yet reproduce the error but identified the problem with reference counting. When updating the tag it correctly updates all members having this tag. However, when updating a member we have a hook updating his tags as required (used by the member activity when tagging members). This hook relies on the following [tag equality function](https://github.com/kalisio/kdk/blob/master/core/api/hooks/hooks.tags.js#L9) to check if tags have changed on the member. Because it has been renamed it detects it as changed and wrongly considers it as added.

**Comment by claustres** [comment] 2020-07-10 11:13
Closing now, will reopen if fixing https://github.com/kalisio/kdk/issues/210 is not sufficient.

**Closed by claustres** 2020-07-10 11:13 UTC
Labels: bug
